version: "3.8"

services:
  whatsdecrypt:
    image: node:18-alpine
    command: >
      sh -c "
      echo 'Iniciando configuração do WhatsDecrypt...' &&
      apk add --no-cache git &&
      echo 'Verificando diretório /app...' &&
      if [ -d '/app/.git' ]; then
        echo 'Repositório já existe, atualizando...' &&
        cd /app &&
        git reset --hard &&
        git pull;
      else
        echo 'Limpando diretório /app...' &&
        rm -rf /app/* /app/.* 2>/dev/null || true &&
        echo 'Clonando repositório...' &&
        git clone https://github.com/jeanjonathas/whatsdecrypt.git /tmp/whatsdecrypt &&
        cp -r /tmp/whatsdecrypt/* /app/ &&
        cp -r /tmp/whatsdecrypt/.* /app/ 2>/dev/null || true &&
        rm -rf /tmp/whatsdecrypt;
      fi &&
      cd /app &&
      echo 'Listando conteúdo do repositório:' &&
      ls -la &&
      echo 'Instalando dependências Node.js...' &&
      npm config set registry https://registry.npmjs.org/ &&
      npm install --no-fund --no-audit &&
      echo 'Verificando estrutura do diretório:' &&
      ls -la &&
      echo 'Conteúdo da pasta src:' &&
      ls -la src/ || echo 'Pasta src não encontrada' &&
      echo 'Conteúdo do package.json:' &&
      cat package.json || echo 'Arquivo package.json não encontrado' &&
      echo 'Iniciando servidor...' &&
      NODE_ENV=production node src/index.js || echo 'Falha ao iniciar o servidor'"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=Je@nfree2525
    volumes:
      - whatsdecrypt_data:/app
    networks:
      - traefik_public
      - app_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.http.routers.whatsdecrypt.rule=Host(`base64.supervet.app`)
        - traefik.http.routers.whatsdecrypt.entrypoints=websecure
        - traefik.http.routers.whatsdecrypt.tls=true
        - traefik.http.routers.whatsdecrypt.tls.certresolver=le
        - traefik.http.services.whatsdecrypt.loadbalancer.server.port=3000
        - traefik.http.services.whatsdecrypt.loadbalancer.passHostHeader=true
        - traefik.http.routers.whatsdecrypt.service=whatsdecrypt
      resources:
        limits:
          cpus: "0.2"
          memory: 128M

volumes:
  whatsdecrypt_data:
    name: whatsdecrypt_data

networks:
  traefik_public:
    external: true
  app_network:
    external: true
