version: '3.8'

services:
  whatsapp-decryptor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-decryptor
    restart: unless-stopped
    networks:
      - traefik_public
      - app_network
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.whatsapp_decryptor.rule=Host(`base64.supervet.app`)
        - traefik.http.routers.whatsapp_decryptor.entrypoints=websecure
        - traefik.http.routers.whatsapp_decryptor.tls.certresolver=le
        - traefik.http.routers.whatsapp_decryptor.service=whatsapp_decryptor
        - traefik.http.services.whatsapp_decryptor.loadbalancer.server.port=3000

networks:
  traefik_public:
    external: true
  app_network:
    external: true
